BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "labels" (
	"id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"colour"	TEXT NOT NULL,
	"dedicated_seconds"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);
INSERT INTO "labels" VALUES (0,'Unlabelled','GRAY',0);
COMMIT;